apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-latest
          imagePullPolicy: IfNotPresent
          image: 'nginx:latest'
      serviceAccount: default
      affinity: {}
      initContainers: []
      volumes: []
      imagePullSecrets: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
